spring:
  application:
    name: authorization
  config:
    import: optional:file:.env[.properties],optional:file:authorization/.env[.properties],optional:file:/app/.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:authorizationdb}
    username: ${POSTGRES_USER:authorizer}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info}
  endpoint:
    health:
      probes:
        enabled: true

bootstrap:
  superuser:
    username: superuser
    password: password
    first-name: Super
    last-name: User

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
   level:
      org:
         springframework:
            security: debug